### ISSUE TITLE
Failed to compile `CSharp.lua.csproj`

### ISSUE THREAD

**Issue by iahung2** [xiaoyuvax/bflata#7]
Doesn't work.

https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/CSharp.lua.csproj

**Comment by xiaoyuvax** [comment]
it's a version matching problem for the nuget packages. wait wait.

**Comment by xiaoyuvax** [comment]
It seems that there's no clue for `.nuget\packages\microsoft.codeanalysis.common\4.8.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll` to be included in the LibBook while it is actually a needed dependency to build. 
Since BflatA does not support parsing path to analyzers, this dependency might have been missed thereby.
You may work it around by manually adding this lib with "-r" option in a .bfa file and include it by using "-inc:xxx.bfa" in BFlatA commandline.

though I did not solve ur problem of "missing the dependency to Microsoft.CodeAnalysis.dll", i solved a bug on the path by allowing matching a version range of package.
